language: python
python:
- '3.6'
- '3.7'
- '3.8'
sudo: false
install:
- python setup.py install
- pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  user: pyratez
  distributions: sdist bdist_wheel bdist_egg
  on:
    tags: true
    all_branches: true
    skip_existing: true
    skip_cleanup: true
  password:
    secure: xn/hkHvLyxDtVT18AkkBuztNQW+Lcnqiimaox6f7PeY/gknDCMZJnXYP6bTi6NkzyKuTHqCviJsytO+aWw8pqwhi85l0J0orAqAsSOZM8rOLS5sIXJ5eTrnFHe9erZJLJhBC2n39sA1UKwnH9SU5pzGqJ399NZQmOM1hjLPLKpiT9WbB1XEec/tL0D+Zh3E90ErhFv0M2oXoAUZQfT+ok+vRdVXaE+jfiyBLmfUbihVl6DrKPW9ZqQyEjMXLjK+uCeTj4gzyonw8mWN3cM8rpVLLHHjIsc1XIX1GcCXoUZ9nXRij9QuqtRaDvEWbq9Gn3ePG00YLxziyg79Cwnz9U3K7SJS9pPhw2RxyGHDRQhcON7RD5GEzVpS58yRJVysFkwK/CwRS38M6FZt4BP3ipI/o5+abpjoSVDz1mNcIE80ijDPZlN1iBelPxu00An3F27WYzDDX57OrAURQDfQPXYfSXhCKIOdTD7ymKk1f8k9qwdRso0SxGi/+vFIvoFLj0HgzKe4CY5qi2I3t90XdCgQR+aTBtEgY5oU0O+zGvva2N7xrRkV5P7HIiBoSjyP+idW7rpovSTMU5czos+yLNAKl35aMWd2BxEmnNieIGweHDoHYCKs+1PU7Dq1vXe80FesMdIpRqO8ZviyvcMyE6zHrZqWLlPkONchhe1eDnxw=
