language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
sudo: false

# before_install: pip install codecov
# after_success:  codecov

install:
  - python setup.py install
  - pip install -r requirements.txt

script: pytest
