name: Continious Integration

on: [pull_request]

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python: [3.8, 3.9]
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e py
